In [1]:
#refer : 0.1.1-Langchain_Setup_New.ipynb (for intial setup)
#refer: 0.1.2-Transformer_setup_n_Langchain_exmpls.ipynb for transformer setup needed to work with HF models/libraries/functions
#Testing embeddings
from langchain_community.embeddings import HuggingFaceEmbeddings
import transformers
print(transformers.__version__)
print(transformers.__file__)
import os
import transformers.models.t5
print(transformers.models.t5.__file__)

4.55.2
e:\Lesson_2_demos\venv\lib\site-packages\transformers\__init__.py
e:\Lesson_2_demos\venv\lib\site-packages\transformers\models\t5\__init__.py


In [2]:
model = "sentence-transformers/all-MiniLM-L6-v2"
embeddings = HuggingFaceEmbeddings(model_name=model)

C:\Users\Ajay\AppData\Local\Temp\ipykernel_11124\3259767528.py:2: LangChainDeprecationWarning: The class `HuggingFaceEmbeddings` was deprecated in LangChain 0.2.2 and will be removed in 1.0. An updated version of the class exists in the `langchain-huggingface package and should be used instead. To use it run `pip install -U `langchain-huggingface` and import as `from `langchain_huggingface import HuggingFaceEmbeddings``.
  embeddings = HuggingFaceEmbeddings(model_name=model)


In [3]:
text = """langchain is a framework for developing llm appls powered by llms.
          It connects different components such as models, prompts, configuration settings """

In [4]:
len(text)

158

In [5]:
test_embedding = embeddings.embed_documents(text)

In [7]:
#test_embedding

In [9]:
#len(test_embedding)
len(test_embedding[0])

384

In [10]:
test_embedding_spec = embeddings.embed_documents(text[0:10])

In [12]:
len(test_embedding_spec[0])

384

In [13]:
test_embedding_spec in test_embedding

False

In [14]:
from sklearn.metrics.pairwise import cosine_similarity
similarity = cosine_similarity(test_embedding_spec,test_embedding)

In [15]:
len(test_embedding), len(test_embedding_spec)

(158, 10)

In [16]:
len(test_embedding[0]), len(test_embedding_spec[0])

(384, 384)

In [17]:
similarity

array([[1.        , 0.51551762, 0.50750906, ..., 0.56249105, 0.48440606,
        0.50507471],
       [0.51551761, 1.        , 0.41358501, ..., 0.43493559, 0.39703985,
        0.41548122],
       [0.50750893, 0.413585  , 1.        , ..., 0.4811575 , 0.43594613,
        0.63493021],
       ...,
       [0.43525899, 0.39859778, 0.5278652 , ..., 0.43167688, 0.4701121 ,
        0.66366865],
       [0.50750893, 0.413585  , 1.        , ..., 0.4811575 , 0.43594613,
        0.63493021],
       [0.50507463, 0.41548113, 0.63493026, ..., 0.49934066, 0.60984257,
        1.        ]])

In [20]:
text1 = "king"
text2 = "queen"
embedding1 = embeddings.embed_documents(text1)
embedding2 = embeddings.embed_documents(text2)
similarity = cosine_similarity(embedding1,embedding2)
#len(embedding1), len(embedding2)
#len(embedding1[0])
similarity

array([[0.5187425 , 0.51439538, 0.55153296, 0.55153296, 0.67049644],
       [0.35258781, 0.6591103 , 0.43294392, 0.43294392, 0.52786521],
       [0.46160831, 0.56096408, 0.58371327, 0.58371327, 1.        ],
       [0.42240362, 0.46004613, 0.50213818, 0.50213818, 0.48115775]])

In [63]:
model

'sentence-transformers/all-MiniLM-L6-v2'

In [23]:
text1 = "king"
text2 = "man"
embedding1 = embeddings.embed_documents(text1)
embedding2 = embeddings.embed_documents(text2)
from sklearn.metrics.pairwise import euclidean_distances
similarity = euclidean_distances([embedding1[0]],[embedding2[0]])
similarity

array([[1.02866449]])

In [24]:
#!pip install gensim
import gensim.downloader as api

# Load a small pretrained word2vec model from gensim-data
# We'll use "glove-wiki-gigaword-50" (50d vectors, ~70MB) for lightweight demo
model = api.load("glove-wiki-gigaword-50")

# Pick a demo word
word = "king"

# Get vector
vector = model[word]

# Get most similar words
similar = model.most_similar(word, topn=5)

vector[:10], similar  # show first 10 values of vector for brevity, plus top 5 similar words

[==================================================] 100.0% 66.0/66.0MB downloaded


(array([ 0.50451 ,  0.68607 , -0.59517 , -0.022801,  0.60046 , -0.13498 ,
        -0.08813 ,  0.47377 , -0.61798 , -0.31012 ], dtype=float32),
 [('prince', 0.8236179351806641),
  ('queen', 0.7839043140411377),
  ('ii', 0.7746230363845825),
  ('emperor', 0.7736247777938843),
  ('son', 0.766719400882721)])

In [ ]:
#to check the dimension size of embeddings created
len(test_embedding[0])

384

In [26]:
text2 = "langchain"

In [27]:
len(text2)

9

In [28]:
test_embedding2 = embeddings.embed_documents(text2)

In [29]:
len(test_embedding2)

9

In [30]:
len(test_embedding2[0])

384

In [ ]:
api_key="myapikey"

In [ ]:
endpoint = "myendpoint"
model_name = "text-embedding-3-small"
deployment = "text-embedding-3-small"
api_version = "2023-05-15"

In [ ]:
#Another option using openai embeddings model
import os
from openai import AzureOpenAI

client = AzureOpenAI(
    api_key=api_key,
    azure_endpoint=endpoint,
    api_version=api_version,
)

response = client.embeddings.create(
    input=["first phrase","second phrase","third phrase"],
    model=deployment
)

for item in response.data:
    length = len(item.embedding)
    print(
        f"data[{item.index}]: length={length}, "
        f"[{item.embedding[0]}, {item.embedding[1]}, "
        f"..., {item.embedding[length-2]}, {item.embedding[length-1]}]"
    )
print(response.usage)

In [66]:
embedding = response.data[0].embedding

In [67]:
len(embedding)

1536

In [68]:
import sklearn

In [75]:
from sklearn.metrics.pairwise import cosine_similarity,euclidean_distances
similarity = cosine_similarity([response.data[0].embedding],[response.data[1].embedding])[0][0]

In [ ]:
similarity

In [ ]:
response = client.embeddings.create(
    input=["tiger","giraffe","third phrase"],
    model=deployment
)

for item in response.data:
    length = len(item.embedding)
    print(
        f"data[{item.index}]: length={length}, "
        f"[{item.embedding[0]}, {item.embedding[1]}, "
        f"..., {item.embedding[length-2]}, {item.embedding[length-1]}]"
    )
print(response.usage)

In [ ]:
from sklearn.metrics.pairwise import cosine_similarity
similarity = cosine_similarity([response.data[0].embedding],[response.data[1].embedding])[0][0]

In [73]:
similarity

0.4946643971411542

In [95]:
#Hugging Face
#word level from BERT
from transformers import AutoTokenizer, AutoModel
import torch

tokenizer = AutoTokenizer.from_pretrained("bert-base-uncased")
model = AutoModel.from_pretrained("bert-base-uncased")

text = "Machine learning is amazing"
inputs = tokenizer(text, return_tensors="pt")

with torch.no_grad():
    outputs = model(**inputs)

# Word embeddings (token embeddings)
word_embeddings = outputs.last_hidden_state  # shape: (1, tokens, hidden_dim)

print(word_embeddings.shape)
print(word_embeddings)

torch.Size([1, 6, 768])
tensor([[[ 0.0354,  0.1103, -0.3218,  ..., -0.3220,  0.2108,  0.4355],
         [-0.0256,  0.0746, -0.2299,  ..., -0.0827,  0.5226,  0.5398],
         [-0.5299,  0.1231, -0.1128,  ..., -1.0709, -0.0107,  0.1068],
         [-0.3427,  0.0282,  0.0928,  ...,  0.0603,  0.0525,  0.5438],
         [-0.3933, -0.3454, -0.4905,  ...,  0.3983,  0.3227, -0.3293],
         [ 0.7771,  0.0532, -0.3531,  ..., -0.0190, -0.7669,  0.0192]]])


In [97]:
#Sentence level embeddings
from sentence_transformers import SentenceTransformer
model = SentenceTransformer("sentence-transformers/all-MiniLM-L6-v2")

sentences = [
    "I love machine learning",
    "AI is fascinating"
]

embeddings = model.encode(sentences)

print(embeddings.shape)  # (2, embedding_dim)
#print(embeddings)

(2, 384)


In [100]:
#Image embeddings
from transformers import AutoImageProcessor, AutoModel
from PIL import Image
import torch

image = Image.open("boarding details.png")

processor = AutoImageProcessor.from_pretrained("google/vit-base-patch16-224")
model = AutoModel.from_pretrained("google/vit-base-patch16-224")

inputs = processor(images=image, return_tensors="pt")

with torch.no_grad():
    outputs = model(**inputs)

image_embeddings = outputs.last_hidden_state[:, 0, :]  # CLS token
print(image_embeddings.shape)
#print(image_embeddings)

Fast image processor class <class 'transformers.models.vit.image_processing_vit_fast.ViTImageProcessorFast'> is available for this model. Using slow image processor class. To use the fast image processor class set `use_fast=True`.
Some weights of ViTModel were not initialized from the model checkpoint at google/vit-base-patch16-224 and are newly initialized: ['pooler.dense.bias', 'pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


torch.Size([1, 768])


In [101]:
#Multi-modal embeddings
from transformers import CLIPProcessor, CLIPModel
from PIL import Image
import torch

model = CLIPModel.from_pretrained("openai/clip-vit-base-patch32")
processor = CLIPProcessor.from_pretrained("openai/clip-vit-base-patch32")

image = Image.open("boarding details.png")
#text = ["a dog", "a cat"]
text = ["Boarding details"]
inputs = processor(text=text, images=image, return_tensors="pt", padding=True)

with torch.no_grad():
    outputs = model(**inputs)

image_embeds = outputs.image_embeds
text_embeds = outputs.text_embeds

print(image_embeds.shape, text_embeds.shape)

torch.Size([1, 512]) torch.Size([1, 512])
